# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protobuf.client_stream import client_stream_pb2 as protobuf_dot_client__stream_dot_client__stream__pb2


class client_streamStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.request = channel.stream_unary(
                '/client_stream.client_stream/request',
                request_serializer=protobuf_dot_client__stream_dot_client__stream__pb2.Request.SerializeToString,
                response_deserializer=protobuf_dot_client__stream_dot_client__stream__pb2.Response.FromString,
                )


class client_streamServicer(object):
    """Missing associated documentation comment in .proto file."""

    def request(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_client_streamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'request': grpc.stream_unary_rpc_method_handler(
                    servicer.request,
                    request_deserializer=protobuf_dot_client__stream_dot_client__stream__pb2.Request.FromString,
                    response_serializer=protobuf_dot_client__stream_dot_client__stream__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'client_stream.client_stream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class client_stream(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def request(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/client_stream.client_stream/request',
            protobuf_dot_client__stream_dot_client__stream__pb2.Request.SerializeToString,
            protobuf_dot_client__stream_dot_client__stream__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
