# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/server_stream/server_stream.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*protobuf/server_stream/server_stream.proto\x12\rserver_stream\"\x17\n\x07Request\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x1a\n\x08Response\x12\x0e\n\x06result\x18\x01 \x01(\t2O\n\rserver_stream\x12>\n\x07request\x12\x16.server_stream.Request\x1a\x17.server_stream.Response\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.server_stream.server_stream_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUEST']._serialized_start=61
  _globals['_REQUEST']._serialized_end=84
  _globals['_RESPONSE']._serialized_start=86
  _globals['_RESPONSE']._serialized_end=112
  _globals['_SERVER_STREAM']._serialized_start=114
  _globals['_SERVER_STREAM']._serialized_end=193
# @@protoc_insertion_point(module_scope)
