# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/client_video/client_video.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(protobuf/client_video/client_video.proto\x12\x0c\x63lient_video\"\x17\n\x07Request\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x1a\n\x08Response\x12\x0e\n\x06result\x18\x01 \x01(\t2L\n\x0c\x63lient_video\x12<\n\x07request\x12\x15.client_video.Request\x1a\x16.client_video.Response\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.client_video.client_video_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUEST']._serialized_start=58
  _globals['_REQUEST']._serialized_end=81
  _globals['_RESPONSE']._serialized_start=83
  _globals['_RESPONSE']._serialized_end=109
  _globals['_CLIENT_VIDEO']._serialized_start=111
  _globals['_CLIENT_VIDEO']._serialized_end=187
# @@protoc_insertion_point(module_scope)
